app/members/urls.py
from django.urls import path

from . import views

app_name = 'members'
urlpatterns = [
    path('facebook-login/', views.facebook_login, name='facebook-login'),
    path('login/', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

app/products/urls/views.py
from django.urls import path


from products.views import exhibition_total_list, exhibition_detail

app_name = 'products'
urlpatterns = [
    path('', exhibition_total_list, name='exhibition'),
    path('<int:pk>/', exhibition_detail, name='exhibition-detail'),
]

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Whatyouwant</title>
</head>
<body>
<nav class="navbar navbar-expand navbar-light bg-light">
    <div class="container">
        <a href="{% url 'index' %}" class="navbar-brand">What <span class="text-info">you</span> want</a>
        <div class="">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <p class="nav-link"><a href="{% url 'members:mypage' %}">{{ user }}</a>님 환영합니다.</p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:signup' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h2><a href="{% url 'products:exhibition' %}">전체보기</a></h2>
    <h2><a href="">전시</a></h2>
    <h2><a href="">뮤지컬</a></h2>
    <h2><a href="">콘서트</a></h2>
    <h2><a href="">연극</a></h2>
    <h2><a href="">클래식</a></h2>
    <h2><a href="">키즈</a></h2>
{% endblock %}